from __future__ import annotations

from typing import Protocol


class BlobStore(Protocol):
    def put(self, content: bytes, *, ref_owner: str, ref_kind: str) -> str: ...

    def get(self, blob_id: str) -> bytes: ...

    def add_reference(self, blob_id: str, *, ref_owner: str, ref_kind: str) -> None: ...

    def release_reference(self, blob_id: str, *, ref_owner: str, ref_kind: str) -> None: ...

    def release_owner(self, ref_owner: str) -> int: ...

    def gc(self) -> int: ...
